service: getok
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  run:
    handler: bin/run
    events:
      - http:
          path: run
          method: post
